export const GET_DATA_FROM_SERVER = 'GET_DATA_FROM_SERVER';

export const SORT_CLIENT_NAME_ASC = 'SORT_CLIENT_NAME_ASC';
export const SORT_CLIENT_NAME_DESC = 'SORT_CLIENT_NAME_DESC';
export const SORT_CLIENT_AUTHOR_ASC = 'SORT_CLIENT_AUTHOR_ASC';
export const SORT_CLIENT_AUTHOR_DESC = 'SORT_CLIENT_AUTHOR_DESC';